"""empty message

Revision ID: bb5ff09273dc
Revises: 
Create Date: 2020-02-28 23:34:45.182103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5ff09273dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compositor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('informacoes', sa.Text(), nullable=True),
    sa.Column('foto', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('permissao', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(), nullable=False),
    sa.Column('cadastrado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emrevisao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('compositores', sa.String(), nullable=False),
    sa.Column('letra', sa.Text(), nullable=False),
    sa.Column('informacoes', sa.Text(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('letra', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enviado_em', sa.DateTime(), nullable=False),
    sa.Column('informacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compositores',
    sa.Column('compositor_id', sa.Integer(), nullable=True),
    sa.Column('musica_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['compositor_id'], ['compositor.id'], ),
    sa.ForeignKeyConstraint(['musica_id'], ['musica.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compositores')
    op.drop_table('musica')
    op.drop_table('emrevisao')
    op.drop_table('usuario')
    op.drop_table('compositor')
    # ### end Alembic commands ###
